<a href="https://colab.research.google.com/github/sergope/tfm/blob/main/extract_pollution_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Conectar el notebook con la cuenta de gdrive
from google.colab import drive
drive.mount('/content/drive/', force_remount=False)

BASE_FOLDER = 'drive/My Drive/TFM/resources/'

Mounted at /content/drive/

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
%run 'drive/My Drive/TFM/resources/enums'.ipynb
magnitudes
estacion_de_medida
indice_contaminantes

{'NO2': {'BUENO': 100,
  'DESCRIPCION': 'Dióxido de Nitrógeno (NO2)',
  'MALO': 400,
  'MUY_BUENO': 40,
  'MUY_MALO': 1000,
  'REGULAR': 200},
 'O3': {'BUENO': 120,
  'DESCRIPCION': 'Ozono (O3)',
  'MALO': 240,
  'MUY_BUENO': 80,
  'MUY_MALO': 600,
  'REGULAR': 180},
 'PM10': {'BUENO': 35,
  'DESCRIPCION': 'Partículas menos de 10 µm (PM10)',
  'MALO': 100,
  'MUY_BUENO': 20,
  'MUY_MALO': 1200,
  'REGULAR': 50},
 'PM2_5': {'BUENO': 20,
  'DESCRIPCION': 'Partículas menos de 2.5 µm (PM2.5)',
  'MALO': 50,
  'MUY_BUENO': 10,
  'MUY_MALO': 800,
  'REGULAR': 25},
 'SO2': {'BUENO': 200,
  'DESCRIPCION': 'Dióxido de Azufre (SO2)',
  'MALO': 500,
  'MUY_BUENO': 100,
  'MUY_MALO': 1250,
  'REGULAR': 350}}

In [ ]:
## Extracción de un csv para una Estación en concreto. Filtrado por municipio

def validate_inputs(years, months, station_name):
  if isinstance(years, list) and isinstance(months, list) and isinstance(station_name, str):
    return True
  else:
    print('years and months must be a list[] and station must be a string')
    print('years is a list: ' + str(isinstance(years, list)))
    print('months is a list: ' + str(isinstance(months, list)))
    print('station is a string: ' + str(isinstance(station_name, str)))
    return False



def get_station_by_name(station_name):
  %run 'drive/My Drive/TFM/resources/enums'.ipynb
  try:
    station = estacion_de_medida[station_name.upper()]
    return station
  except:
    print('station: "' + station_name + '" does not exists')



def extract_data_by_station(years, months, station_name):
  if not validate_inputs(years, months, station_name):
    return

  station_data = get_station_by_name(station_name)
  if not station_data:
    return
  
  all_years = []
  for year in years:
    filtered_months = []
    for month in months:
      file_name = str(year) + month + '.csv'
      try:
        table = pd.read_table(BASE_FOLDER+'data/' + str(year) + '/' + file_name, sep=';', engine='python')
        table.columns = table.columns.str.upper()
        filtered_months.append(table[table['MUNICIPIO'] == station_data['municipio']])
      except:
        print('File: "' + BASE_FOLDER+'data/' + str(year) + '/' + file_name + '" does not exists')
        pass

    all_years.append(pd.concat(filtered_months))
    print('Year ' + str(year) + ' loaded')

  final_table = pd.concat(all_years)
  final_table.to_csv(BASE_FOLDER + 'processed_data/' +  station_name.lower() + '.csv', sep = ';', na_rep = 'null')
  print('Process finished. File path: ' + BASE_FOLDER + 'processed_data/' +  station_name.lower() + '.csv')

In [ ]:
#Generamos el csv de GETAFE

years = np.arange(2005,2020).tolist()  #desde el año 2005 hasta 2020
months = ['_01', '_02', '_03', '_04', '_05', '_06', '_07', '_08', '_09', '_10', '_11', '_12']
station = 'getafe'

extract_data_by_station(years, months, station)

Year 2005 loaded
Year 2006 loaded
Year 2007 loaded
Year 2008 loaded
Year 2009 loaded
Year 2010 loaded
Year 2011 loaded
Year 2012 loaded
Year 2013 loaded
Year 2014 loaded
Year 2015 loaded
Year 2016 loaded
Year 2017 loaded
Year 2018 loaded
Year 2019 loaded
Process finished. File path: drive/My Drive/TFM/resources/processed_data/getafe.csv

In [ ]:
table = pd.read_table(BASE_FOLDER+'processed_data/' + 'getafe' + '.csv', sep=';', engine='python')
table

       Unnamed: 0  PROVINCIA  MUNICIPIO  ESTACION  ...    H23 V23    H24  V24
0              93         28         65        14  ...    NaN   N    NaN    N
1              94         28         65        14  ...    NaN   N    NaN    N
2              95         28         65        14  ...    NaN   N    NaN    N
3              96         28         65        14  ...    NaN   N    NaN    N
4             217         28         65        14  ...    NaN   N    NaN    N
...           ...        ...        ...       ...  ...    ...  ..    ...  ...
16083        4947         28         65        14  ...  104.0   V   88.0    V
16084        4948         28         65        14  ...   62.0   V   91.0    V
16085        4949         28         65        14  ...   85.0   V  138.0    V
16086        4950         28         65        14  ...  568.0   V  515.0    V
16087        4951         28         65        14  ...    3.0   V    3.0    V

[16088 rows x 57 columns]